### ISSUE TITLE
how can i find keyid and key

### ISSUE THREAD

**Issue by waqarr** [DRM-Scripts/MPD-Player#1]
dear sir how can i find keyid and key from this data

`<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:dvb="urn:dvb:dash:dash-extensions:2014-1" xmlns:move="http://www.movenetworks.com/dash/v1" xmlns:ms="urn:microsoft" xmlns:_XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" _XMLSchema-instance:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" maxSegmentDuration="PT2.048000S" minBufferTime="PT2.048000S" publishTime="2023-02-21T17:10:00Z" type="dynamic" minimumUpdatePeriod="PT2.048000S" availabilityStartTime="2023-02-21T17:10:15Z" mediaPresentationDuration="PT9000.000000S" suggestedPresentationDelay="PT4.096000S">
    <ProgramInformation>
        <Linear xmlns="http://www.movenetworks.com/dash/v1">true</Linear>
        <Gaps xmlns="http://www.movenetworks.com/dash/v1" possible="false"></Gaps>
    </ProgramInformation>
    <Period id="1" duration="PT9000.000000S" start="PT0.000000S">
        <BaseURL serviceLocation="15804-Fastly" dvb:priority="1" dvb:weight="34">http://p-cdn4-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <BaseURL serviceLocation="15804-Akamai" dvb:priority="1" dvb:weight="33">http://p-cdn1-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <BaseURL serviceLocation="15804-Level3" dvb:priority="1" dvb:weight="33">http://p-cdn3-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <BaseURL serviceLocation="15804-Fastly" dvb:priority="2" dvb:weight="34">http://p-cdn4-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <BaseURL serviceLocation="15804-Akamai" dvb:priority="2" dvb:weight="33">http://p-cdn1-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <BaseURL serviceLocation="15804-Level3" dvb:priority="2" dvb:weight="33">http://p-cdn3-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <BaseURL serviceLocation="15804-Fastly" dvb:priority="3" dvb:weight="34">http://p-cdn4-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <BaseURL serviceLocation="15804-Akamai" dvb:priority="3" dvb:weight="33">http://p-cdn1-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <BaseURL serviceLocation="15804-Level3" dvb:priority="3" dvb:weight="33">http://p-cdn3-804-cg14-linear-cbd46b77.movetv.com/15804/live/WLLOHD-2/2dbe6f0ab15911edaa790025b5471114/</BaseURL>
        <AdaptationSet contentType="audio" mimeType="audio/mp4" segmentAlignment="true" startWithSAP="1" codecs="mp4a.40.2" lang="en">
            <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="488a9299-44ce-41a0-918a-157dfde56ee0" xmlns:v1="http://www.movenetworks.com/dash/v1" v1:widevineProxy="http://p-drmwv.movetv.com/widevine/proxy"></ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95" value="MSPR 2.0">
                <cenc:pssh>AAADMnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAxISAwAAAQABAAgDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwATABBAF8AVQBSAEwAPgBoAHQAdABwADoALwAvAHAALQBwAGwAYQB5AHIAZQBhAGQAeQAuAG0AbwB2AGUAdAB2AC4AYwBvAG0ALwBwAGwAYQB5AHIAZQBhAGQAeQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AcAAtAHAAbABhAHkAcgBlAGEAZAB5AC4AbQBvAHYAZQB0AHYALgBjAG8AbQAvAGwAbwBnAGkAbgAuAGEAcwBwAHgAPAAvAEwAVQBJAF8AVQBSAEwAPgA8AEsASQBEAD4AbQBaAEsASwBTAE0ANQBFAG8ARQBHAFIAaQBoAFYAOQAvAGUAVgB1ADQAQQA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgB4ADgAdABwAEMAYgA5AFoAWgBTAHcAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</cenc:pssh>
            </ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
                <cenc:pssh>AAAAXnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAD4IARIgNDg4YTkyOTk0NGNlNDFhMDkxOGExNTdkZmRlNTZlZTAaB3NsaW5ndHYiCFdMTE9IRC0yKgVTRF9IRA==</cenc:pssh>
                <ms:laurl licenseUrl="http://p-drmwv.movetv.com/widevine/proxy"/>
            </ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
                <cenc:pssh>AAAAIHBzc2gAAAAAEHfv7MCyTQKs4zweUuL7SwAAAAA=</cenc:pssh>
            </ContentProtection>
            <SegmentTemplate timescale="1000" duration="2048" startNumber="37207" initialization="audio/$RepresentationID$/init.mp4" media="audio/$RepresentationID$/$Number%08x$.m4s" presentationTimeOffset="76200353"></SegmentTemplate>
            <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"></AudioChannelConfiguration>
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"></Role>
            <Representation id="stereo/192" audioSamplingRate="48000" bandwidth="196608" qualityRanking="0"></Representation>
            <Representation id="stereo/160" audioSamplingRate="48000" bandwidth="163840" qualityRanking="1"></Representation>
            <Representation id="stereo/128" audioSamplingRate="48000" bandwidth="131072" qualityRanking="2"></Representation>
            <InbandEventStream schemeIdUri="www.nielsen.com:id3:v1" value="1"></InbandEventStream>
        </AdaptationSet>
        <AdaptationSet contentType="video" mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
            <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="488a9299-44ce-41a0-918a-157dfde56ee0" xmlns:v1="http://www.movenetworks.com/dash/v1" v1:widevineProxy="http://p-drmwv.movetv.com/widevine/proxy"></ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95" value="MSPR 2.0">
                <cenc:pssh>AAADMnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAxISAwAAAQABAAgDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwATABBAF8AVQBSAEwAPgBoAHQAdABwADoALwAvAHAALQBwAGwAYQB5AHIAZQBhAGQAeQAuAG0AbwB2AGUAdAB2AC4AYwBvAG0ALwBwAGwAYQB5AHIAZQBhAGQAeQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AcAAtAHAAbABhAHkAcgBlAGEAZAB5AC4AbQBvAHYAZQB0AHYALgBjAG8AbQAvAGwAbwBnAGkAbgAuAGEAcwBwAHgAPAAvAEwAVQBJAF8AVQBSAEwAPgA8AEsASQBEAD4AbQBaAEsASwBTAE0ANQBFAG8ARQBHAFIAaQBoAFYAOQAvAGUAVgB1ADQAQQA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgB4ADgAdABwAEMAYgA5AFoAWgBTAHcAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</cenc:pssh>
            </ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
                <cenc:pssh>AAAAXnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAD4IARIgNDg4YTkyOTk0NGNlNDFhMDkxOGExNTdkZmRlNTZlZTAaB3NsaW5ndHYiCFdMTE9IRC0yKgVTRF9IRA==</cenc:pssh>
                <ms:laurl licenseUrl="http://p-drmwv.movetv.com/widevine/proxy"/>
            </ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
                <cenc:pssh>AAAAIHBzc2gAAAAAEHfv7MCyTQKs4zweUuL7SwAAAAA=</cenc:pssh>
            </ContentProtection>
            <Accessibility schemeIdUri="urn:scte:dash:cc:cea-608:2015" value="CC1=eng"></Accessibility>
            <Accessibility schemeIdUri="urn:scte:dash:cc:cea-708:2015" value="1=lang:eng"></Accessibility>
            <SegmentTemplate timescale="1000" duration="2048" startNumber="37207" initialization="video/$RepresentationID$/init.mp4" media="video/$RepresentationID$/$Number%08x$.m4s" presentationTimeOffset="76200353"></SegmentTemplate>
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"></Role>
            <Representation id="vid05" bandwidth="4300800" codecs="avc1.640028" width="1280" height="720" frameRate="25000/1000" sar="1:1" qualityRanking="0"></Representation>
            <Representation id="vid04" bandwidth="2867200" codecs="avc1.640028" width="1280" height="720" frameRate="25000/1000" sar="1:1" qualityRanking="1"></Representation>
            <Representation id="vid03" bandwidth="1536000" codecs="avc1.4d401f" width="768" height="432" frameRate="25000/1000" sar="1:1" qualityRanking="2"></Representation>
            <Representation id="vid02" bandwidth="819200" codecs="avc1.4d401f" width="768" height="432" frameRate="25000/1000" sar="1:1" qualityRanking="3"></Representation>
            <Representation id="vid01" bandwidth="319488" codecs="avc1.4d401f" width="512" height="288" frameRate="25000/1000" sar="1:1" qualityRanking="4"></Representation>
        </AdaptationSet>
    </Period>
</MPD>
`

**Comment by DRM-Scripts** [comment]
Well the KeyID is literally in what you've copied and pasted, and you can try a site like cdrm-project to find the key or following on of the many tutorials online like: https://forum.videohelp.com/threads/404994-Decryption-and-the-Temple-of-Doom
