### ISSUE TITLE
Added channels do not appear

### ISSUE THREAD

**Issue by ljccitterio** [DRM-Scripts/MPD-Player#13]
Greetings...

In version 3, after importing the MPDs file_mpd.json and its keys or adding channels from the NEW button, the configured MPDs are not shown in the "Channels" section. In version 2 they show up perfectly.

**Comment by dreambox43** [comment]
hello where can we find the keys

**Comment by andremxmx** [comment]
it's a bug, we need to fix it


> Greetings...
> 
> In version 3, after importing the MPDs file_mpd.json and its keys or adding channels from the NEW button, the configured MPDs are not shown in the "Channels" section. In version 2 they show up perfectly.

**Comment by andremxmx** [comment]
> hello where can we find the keys

you need to know how to get the keys, if you don't know how, the best option you have is to go to videohelper forum and learn and ask in the community, so you will be learning how to do it, is the best option

**Comment by KoYeThway** [comment]
> 

where is community. please

**Comment by kjassim64** [comment]
https://forum.videohelp.com/threads/408557-Decryption-The-Last-Crusade
https://forum.videohelp.com/threads/407216-Decryption-The-Dungeon-of-Despair
https://forum.videohelp.com/threads/404994-Decryption-and-the-Temple-of-Doom

**Comment by kjassim64** [comment]
> > 
> 
> où est la communauté. S’il vous plaît
https://forum.videohelp.com/threads/408557-Decryption-The-Last-Crusade
https://forum.videohelp.com/threads/407216-Decryption-The-Dungeon-of-Despair
https://forum.videohelp.com/threads/404994-Decryption-and-the-Temple-of-Doom
