### ISSUE TITLE
streams

### ISSUE THREAD

**Issue by Omegasinus** [DRM-Scripts/MPD-Player#2]
Hi  just installed your great job  man but see any streams on it?

Regards

**Comment by DRM-Scripts** [comment]
The player/panel doesn’t come with streams you could try the following in the panel but you need mpd url & Key:Kid 

Get the KID from MPD and use the key at bottom for all.

```
IT DAZN| Eurosport 1
https://dcf-de-livedazn.daznedge.net/dashdrm/dazn-linear-029/stream.mpd

IT DAZN| Eurosport 2
https://dcf-de-livedazn.daznedge.net/dashdrm/dazn-linear-030/stream.mpd

IT DAZN| Zona Dazn
https://dcf-de-livedazn.daznedge.net/dashdrm/dazn-linear-024/stream.mpd

IT DAZN| Milan TV
https://dce-de-livedazn.daznedge.net/dashdrm/dazn-linear-025/stream.mpd

IT DAZN| NFL Network
https://dcf-de-livedazn.daznedge.net/dashdrm/dazn-linear-023/stream.mpd

IT DAZN| Unbeaten
https://dcf-de-livedazn.daznedge.net/dashdrm/dazn-linear-044/stream.mpd

IT DAZN| Red Bull TV
https://dcf-de-livedazn.daznedge.net/dashdrm/dazn-linear-036/stream.mpd

IT DAZN| Inter TV
https://dcf-de-livedazn.daznedge.net/dashdrm/dazn-linear-033/stream.mpd

All Key: 82f8e2a17dac44c0a18f660479349c59:1b144f73e6fefe91cd05f850e2b589d0
```

**Comment by Omegasinus** [comment]
thanks for your reaply man wil try this

**Comment by Omegasinus** [comment]
is succed installed KID also alos find
i was asking my self were i can find mpd streams/and the key

Thanks in advance 
Kinds

**Comment by DRM-Scripts** [comment]
> is succed installed KID also alos find i was asking my self were i can find mpd streams/and the key
> 
> Thanks in advance Kinds

Literally everything you need is above for a test. For other stuff search google as there is a popular video forum which describes how to do everything in there stickied posts.

**Comment by Omegasinus** [comment]
thanks for you replay i thing you mean video.....
is beter to cancel the key here bro.

**Comment by DRM-Scripts** [comment]
To be honest I don’t care if things get shared as it’s the whole point of posting stuff 😂 keys change the stuff posted is a guide and after that you have to work things out for yourselves. The key will change as it always does.

**Comment by Omegasinus** [comment]
Is true wat you said....is changing evrytime.....but in few days  learn a much with your script and you work  very appereciat it  is most importante

**Comment by Omegasinus** [comment]
Hi man 
im trying to export streams that i added to the panel and working on panel...only 2 no image or sound..other oks 

i get this error when try to export
![image](https://user-images.githubusercontent.com/127033084/224718138-b4f8822f-028f-4625-b26e-3dce40c4ceeb.png)
Greats
