### ISSUE TITLE
admin/123

### ISSUE THREAD

**Issue by Omegasinus** [DRM-Scripts/MPD-Player#3]
Hi cant log with this admin/123

Regards

**Comment by exalted777** [comment]
Hi, which error do you have? 

you can set password manualy here: 
/opt/mpdplayer/mpd.conf & /etc/mpdplayer/mpd.conf

"secret = GA0LXQs9C40YHRgtGA0LDRhtC40Lgg" to put 123

**Comment by Omegasinus** [comment]
hi  thanks for your message

got this error  [cid:dfd2abf5-9923-4b93-8884-fc2fdc6041cf]

i wil first try wat you said

Regards
________________________________
Van: exalted777 ***@***.***>
Verzonden: maandag 20 maart 2023 23:16
Aan: DRM-Scripts/MPD-Player ***@***.***>
CC: Omegasinus ***@***.***>; Author ***@***.***>
Onderwerp: Re: [DRM-Scripts/MPD-Player] admin/123 (Issue #3)


Hi, which error do you have?

you can set password manualy here:
/opt/mpdplayer/mpd.conf & /etc/mpdplayer/mpd.conf

"secret = GA0LXQs9C40YHRgtGA0LDRhtC40Lgg" to put 123

**Comment by Omegasinus** [comment]
hi
i did the change but stil have same issue

if i look to the logs  see this

2023-03-20 23:26:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found (this database is empty); SQL statement:
SELECT USERS.ID, USERS.LOGIN, USERS.PASS, USERS.EXPIRATION, USERS."ROLE" FROM USERS WHERE (USERS.LOGIN = ?) AND (USERS.PASS = ?) [42104-214]
2023-03-20 23:28:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found (this database is empty); SQL statement:
SELECT USERS.ID, USERS.LOGIN, USERS.PASS, USERS.EXPIRATION, USERS."ROLE" FROM USERS WHERE (USERS.LOGIN = ?) AND (USERS.PASS = ?) [42104-214]
2023-03-20 23:28:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found (this database is empty); SQL statement:
SELECT USERS.ID, USERS.LOGIN, USERS.PASS, USERS.EXPIRATION, USERS."ROLE" FROM USERS WHERE (USERS.LOGIN = ?) AND (USERS.PASS = ?) [42104-214]
2023-03-20 23:31:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found (this database is empty); SQL statement:
SELECT USERS.ID, USERS.LOGIN, USERS.PASS, USERS.EXPIRATION, USERS."ROLE" FROM USERS WHERE (USERS.LOGIN = ?) AND (USERS.PASS = ?) [42104-214]

________________________________
Van: exalted777 ***@***.***>
Verzonden: maandag 20 maart 2023 23:16
Aan: DRM-Scripts/MPD-Player ***@***.***>
CC: Omegasinus ***@***.***>; Author ***@***.***>
Onderwerp: Re: [DRM-Scripts/MPD-Player] admin/123 (Issue #3)


Hi, which error do you have?

you can set password manualy here:
/opt/mpdplayer/mpd.conf & /etc/mpdplayer/mpd.conf

"secret = GA0LXQs9C40YHRgtGA0LDRhtC40Lgg" to put 123

**Comment by DRM-Scripts** [comment]
Are you connected to the correct DB file? As it saying it can’t find the user/pass within the db query.

make sure have renaming old conf and replacing you have restarted the service.
