### ISSUE TITLE
V3.0 Can't add channel

### ISSUE THREAD

**Issue by iptvtest123** [DRM-Scripts/MPD-Player#4]
V3.0 Can't add channel

**Comment by LiamKenyon** [comment]
Need a little more info… as it’s fairly straight forward to add a channel, so any errors show etc…

**Comment by iptvtest123** [comment]
yes,Thank you for your reply. I have chosen a channel provider. Still not adding channels

**Comment by thejackal2017** [comment]
- Try to add a new link , it won' add if the link was added before . 
- make sure to use the correct database/config file 
- if problem persist try logout then login again

**Comment by iptvtest123** [comment]
Thank you very much for your reply. Do you have Whatsapp and Telearm that you can contact to help me?

**Comment by thejackal2017** [comment]
yes i have , but unfortunately there is no private messages feature on github . Anyway you can leav your telegram so i can reach you . 

Back to the problem , please make sure you have put the right permissions for the /opt/mpdplayer directory  and try again .

regards

**Comment by iptvtest123** [comment]
https://t.me/chineseiptv)

**Comment by paulodbs21** [comment]
I can't add channel either.

**Comment by iptvtest123** [comment]
Sort first

**Comment by paulodbs21** [comment]
> Sort first

do you have drm keys?
